---
- hosts: localhost
  vars_files:
  - us-east-1.yaml     #here we cast pass the value baska bir note da yazabilirsin 
  tasks:

- name: Created instances         #all everthing is now soft coded :)
  ec2:
    key_name: "{{key_name}}"
    instance_type: "{{instance_type}}"
    image: "{{image}}"
    group: "{{group}}"
    count: "{{count}}"
    vpc_subnet_id: "{{vpc_subnet_id}}"
    assign_public_ip: "{{assign_public_ip}}"
    region: "{{region}}"