---
- hosts: localhost       #localhost do only in your machine            
  tasks:

  - name: example using security group rule descriptions
    ec2_group:
      name: Allow80
      description: "sg with rule descriptions"
      region: us-east-1
      rules:
        - proto: tcp
          ports:
          - 80
          cidr_ip: 0.0.0.0/0
          